### ISSUE TITLE
jira-dashboard alpha entityJiraContent functionality

### ISSUE THREAD

**Issue by eddiehale3** [AxisCommunications/backstage-plugins#296]
I was working on upgrading this repo to 1.38.1 and ran across an issue in `backstage-plugins/plugins/jira-dashboard/src/alpha/entityContent.tsx`

```
$ yarn build:api-reports

TIP: You can generate api-reports for select packages by passing package paths:

       yarn build:api-reports packages/config packages/core-plugin-api plugins/*

# Compiling TypeScript
plugins/jira-dashboard/src/alpha/entityContent.tsx:13:14 - error TS2742: The inferred type of 'entityJiraContent' cannot be named without a reference to '@backstage/plugin-catalog/node_modules/@backstage/catalog-model'. This is likely not portable. A type annotation is necessary.

13 export const entityJiraContent = EntityContentBlueprint.makeWithOverrides({
                ~~~~~~~~~~~~~~~~~


Found 1 error in plugins/jira-dashboard/src/alpha/entityContent.tsx:13
```

This is my only error and I'm unable to generate api-reports. Should the `entityJiraContent` alpha functionality be moved with the other components? I'm not that familiar with jira-dashboard and don't want to refactor anything that might cause issues.

**Comment by eddiehale3** [comment]
@fridajac PR uploaded, I haven't created the changeset yet. 

https://github.com/AxisCommunications/backstage-plugins/pull/297

**Comment by anicke** [comment]
We have bumped all the related packages to 1.40 now, hope that works for you!
